# .github/workflows/ci.yml
name: CI/CD Pipeline
on: [pull_request, workflow_dispatch] #manually run workflow 
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository #whoever is doing PR 
        uses: actions/checkout@v4
      - name: Setup Node.js #installs node js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install dependencies #3rd step
        run: |
          yarn
      - name: Run unit tests #;ast final step
        run: |
          NODE_ENV=production yarn test